workflows:
  release-workflow:
    name: Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      groups:
        - google_play
    scripts:
      - name: Get Flutter packages
        script: flutter pub get
      - name: Build AAB for release
        script: flutter build appbundle --release
    artifacts:
      - build/app/outputs/bundle/release/*.aab
    publishing:
      google_play:
        credentials: Encrypted(GOOGLE_PLAY_JSON)
        track: production   # internal | beta | production
        in_app_update_priority: 3
        changes_not_sent_for_review: false
